controller_list:
  - name: fake_dofbot_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_01
      - arm_joint_02
      - arm_joint_03
      - arm_joint_04
      - arm_joint_05
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - grip_joint
initial:  # Define initial robot poses per group
  - group: dofbot
    pose: up
  - group: gripper_group
    pose: close